language: ruby
rvm:
  - 2.3.0
env:
  - CODECLIMATE_REPO_TOKEN=e8fbc5d14be5ba100ae22c6bcfcc87caada77f23e0e462f4bf615fa1576e850d
  - COVERALLS_REPO_TOKEN=WTsbiG2zuXloeywC1XEP9oZzsgGnO4jZi
before_install: gem install bundler -v 1.11.2
script: bundle exec rake test
